### ISSUE TITLE
Error while serialising user stats in v6

### ISSUE THREAD

**Issue by BlackCrawler** [wight-airmash/ab-server#109]
log:
```
{"level":50,"time":1586729005469,"msg":"Error while serialising user stats: {\"error\":\"Error: Item at 1 does not match schema definition.\\n    at $arr$maini (eval at build (/app/node_modules/fast-json-stringify/index.js:1:1), <anonymous>:155:13)\\n    at Object.$main [as stringifyUserStats] (eval at build (/app/node_modules/fast-json-stringify/index.js:1:1), <anonymous>:127:17)\\n    at UserStatsPeriodic.serializeData (/app/dist/server/periodic/user-stats/user-stats.js:77:54)\\n    at UserStatsPeriodic.save (/app/dist/server/periodic/user-stats/user-stats.js:59:18)\\n    at UserStatsPeriodic.onSecondTick (/app/dist/server/periodic/user-stats/user-stats.js:35:22)\\n    at EventEmitter.emit (/app/node_modules/eventemitter3/index.js:203:33)\\n    at GameClock.emit (/app/dist/server/system.js:18:25)\\n    at GameClock.onTick (/app/dist/server/maintenance/clock.js:56:22)\\n    at EventEmitter.emit (/app/node_modules/eventemitter3/index.js:210:27)\\n    at GameServerBootstrap.emitLoopEventsGroup (/app/dist/core/bootstrap.js:191:25)\"}"}
```
Do you need sample of json file or something like that?

**Comment by wight-airmash** [comment]
If this error is repeated after restarting the server, then yes, a sample be useful. If not, I will try to find the reason without it.

**Comment by BlackCrawler** [comment]
This error disappeared even without restart.
It occurred every 10 seconds.

**Comment by wight-airmash** [comment]
The bug is related to just created accounts. It's interesting the error disappeared without restart.
